const DashBorardArray = [
  {
    id: 1,
    reviewID: 1,
    userId: 1,
    courseId: 1,
    titleName: 'Ansible 자동화로 구현한 아마존 AWS 클라우드 환경 DevOps',
    reviewStatus: '심사중',
    courseLocation: '온라인',
    userMajor: '비전공자',
    userFinish: '수강중',
    reviewDate: '2024-07-11',
    courseInstructor: '강사명',
    courseTeam: false,
    reviewRate: 4,
    reviewPro: '좋았던 점',
    reviewCon: '아쉬웠던 점',
    reviewProposal: '학습에 바라는 점',
    reviewRecommend: true,
    reviewCertImg: 'https://내일모배우지.com/certimg.jpg',
    reviewList: [
      {
        id: 1,
        reviewStatus: '심사중',
        courseLocation: '온라인',
        userMajor: '비전공자',
        userFinish: '수강중',
        reviewDate: '2024-07-11',
        courseInstructor: '강사명',
        courseTeam: false,
        reviewRate: 4,
        reviewPro: '좋았던 점',
        reviewCon: '아쉬웠던 점',
        reviewProposal: '학습에 바라는 점',
        reviewRecommend: true,
      },
      {
        id: 2,
        reviewStatus: '심사중',
        courseLocation: '온라인',
        userMajor: '비전공자',
        userFinish: '수강중',
        reviewDate: '2024-07-11',
        courseInstructor: '강사명',
        courseTeam: false,
        reviewRate: 4,
        reviewPro: '좋았던 점',
        reviewCon: '아쉬웠던 점',
        reviewProposal: '학습에 바라는 점',
        reviewRecommend: true,
      },
      {
        id: 3,
        reviewStatus: '심사중',
        courseLocation: '온라인',
        userMajor: '비전공자',
        userFinish: '수강중',
        reviewDate: '2024-07-11',
        courseInstructor: '강사명',
        courseTeam: false,
        reviewRate: 4,
        reviewPro: '좋았던 점',
        reviewCon: '아쉬웠던 점',
        reviewProposal: '학습에 바라는 점',
        reviewRecommend: true,
      },
      {
        id: 4,
        reviewStatus: '심사중',
        courseLocation: '온라인',
        userMajor: '비전공자',
        userFinish: '수강중',
        reviewDate: '2024-07-11',
        courseInstructor: '강사명',
        courseTeam: false,
        reviewRate: 4,
        reviewPro: '좋았던 점',
        reviewCon: '아쉬웠던 점',
        reviewProposal: '학습에 바라는 점',
        reviewRecommend: true,
      },
    ],
  },
  {
    id: 2,
    reviewID: 2,
    userId: 2,
    courseId: 2,
    reviewStatus: '심사완료',
    courseLocation: '오프라인',
    userMajor: '전공자',
    userFinish: '수료',
    reviewDate: '2024-07-12',
    courseInstructor: '다른 강사명',
    courseTeam: true,
    reviewRate: 5,
    reviewPro: '또 다른 좋았던 점',
    reviewCon: '또 다른 아쉬웠던 점',
    reviewProposal: '또 다른 학습에 바라는 점',
    reviewRecommend: false,
    reviewCertImg: 'https://내일모배우지.com/anothercertimg.jpg',
  },
  {
    id: 3,
    reviewID: 2,
    userId: 2,
    courseId: 2,
    reviewStatus: '심사완료',
    courseLocation: '오프라인',
    userMajor: '전공자',
    userFinish: '수료',
    reviewDate: '2024-07-12',
    courseInstructor: '다른 강사명',
    courseTeam: true,
    reviewRate: 5,
    reviewPro: '또 다른 좋았던 점',
    reviewCon: '또 다른 아쉬웠던 점',
    reviewProposal: '또 다른 학습에 바라는 점',
    reviewRecommend: false,
    reviewCertImg: 'https://내일모배우지.com/anothercertimg.jpg',
  },
  {
    id: 4,
    reviewID: 2,
    userId: 2,
    courseId: 2,
    reviewStatus: '심사완료',
    courseLocation: '오프라인',
    userMajor: '전공자',
    userFinish: '수료',
    reviewDate: '2024-07-12',
    courseInstructor: '다른 강사명',
    courseTeam: true,
    reviewRate: 5,
    reviewPro: '또 다른 좋았던 점',
    reviewCon: '또 다른 아쉬웠던 점',
    reviewProposal: '또 다른 학습에 바라는 점',
    reviewRecommend: false,
    reviewCertImg: 'https://내일모배우지.com/anothercertimg.jpg',
  },
  {
    id: 5,
    reviewID: 2,
    userId: 2,
    courseId: 2,
    reviewStatus: '심사완료',
    courseLocation: '오프라인',
    userMajor: '전공자',
    userFinish: '수료',
    reviewDate: '2024-07-12',
    courseInstructor: '다른 강사명',
    courseTeam: true,
    reviewRate: 5,
    reviewPro: '또 다른 좋았던 점',
    reviewCon: '또 다른 아쉬웠던 점',
    reviewProposal: '또 다른 학습에 바라는 점',
    reviewRecommend: false,
    reviewCertImg: 'https://내일모배우지.com/anothercertimg.jpg',
  },
];
export default DashBorardArray;
